import { App, Notice } from 'obsidian';
import { DUMMY_ASSETS } from './DemoAssets';

export class ShowcaseGenerator {
    private app: App;
    private basePath = 'GalleryDemo';
    private assetsPath = 'GalleryDemo/Assets';

    constructor(app: App) {
        this.app = app;
    }

    async generateShowcase(): Promise<void> {
        try {
            // Check if folder already exists
            const existingFolder = this.app.vault.getAbstractFileByPath(this.basePath);
            if (existingFolder) {
                new Notice(`${this.basePath} already exists. Delete or rename it if you want to regenerate the showcase.`);
                return;
            }

            // Create folders
            await this.createFolderSafe(this.basePath);
            await this.createFolderSafe(this.assetsPath);
            await this.createFolderSafe(`${this.assetsPath}/Nature`);
            await this.createFolderSafe(`${this.assetsPath}/Travel`);
            await this.createFolderSafe(`${this.assetsPath}/EmptyFolder`);

            // Write dummy assets into sub-folders too
            await this.writeDummyAssets();

            // Create showcase notes
            await this.createWelcomeNote();
            await this.createLocalSourceNote();
            await this.createExternalUrlsNote();
            await this.createViewsNote();
            await this.createMixedSourcesNote();
            await this.createSortAndLimitNote();
            await this.createRecursiveAndFiltersNote();
            await this.createImmichAuthenticatedNote();
            await this.createImmichFavoritesRecentNote();
            await this.createImmichAlbumsNote();
            await this.createImmichSharedLinkNote();
            await this.createImmichPasswordNote();
            await this.createErrorStatesNote();

            new Notice('Gallery view showcase generated successfully in gallerydemo');
        } catch (error) {
            console.error('Failed to generate showcase:', error);
            new Notice('Failed to generate showcase. Check console for details.');
        }
    }

    private async createFolderSafe(path: string): Promise<void> {
        const exists = await this.app.vault.adapter.exists(path);
        if (!exists) {
            await this.app.vault.adapter.mkdir(path);
        }
    }

    private async writeDummyAssets(): Promise<void> {
        // Split assets across root, Nature, and Travel sub-folders
        const subFolders = [this.assetsPath, `${this.assetsPath}/Nature`, `${this.assetsPath}/Travel`];
        for (let i = 0; i < DUMMY_ASSETS.length; i++) {
            const base64Data = DUMMY_ASSETS[i];
            const binaryString = window.atob(base64Data);
            const bytes = new Uint8Array(binaryString.length);
            for (let j = 0; j < binaryString.length; j++) {
                bytes[j] = binaryString.charCodeAt(j);
            }
            const folder = subFolders[i % subFolders.length];
            await this.app.vault.createBinary(`${folder}/demo-${i + 1}.jpg`, bytes.buffer);
        }
    }

    private async createWelcomeNote(): Promise<void> {
        const content = `\
# Welcome to Gallery View Showcase

This folder (\`GalleryDemo/\`) was generated by the **Gallery View** plugin to help you explore its features.

You are safe to edit, move, or delete any of these files!

> 💡 **Tip:** Use the **"Insert gallery"** command (Cmd/Ctrl + P → "Insert gallery") to build gallery blocks interactively without writing YAML by hand.

## What is this?
These notes contain examples of how to configure image galleries inside your vault.

### 🖼 Local & External Demos
These notes render images immediately:
- [[01 - Local source]] — Load images from a folder in your vault.
- [[02 - External URLs]] — Load images from web URLs.
- [[03 - Views]] — Three layout types: thumbnail, grid, carousel.
- [[04 - Mixed sources]] — Combine local + external in one gallery.
- [[05 - Sort and limit]] — Control order and count of displayed images.
- [[06 - Recursive and filters]] — Scan sub-folders and filter by date or type.

### 🔐 Immich — Authenticated
Connect to your own Immich server using an API key configured in plugin settings:
- [[07 - Immich authenticated]] — People, tags, and date filters.
- [[08 - Immich favorites and recent]] — Favorites and recent photo feeds.
- [[09 - Immich albums]] — Album-based gallery (template).

### 🔗 Immich — Shared Links
No account required, just a public share URL:
- [[10 - Immich shared link]] — Public shared album.
- [[11 - Password-protected Immich share]] — Password-protected share.

### ⚠️ Error States Reference
See every compact error the plugin can show — great for debugging your own galleries:
- [[12 - Error states]] — One intentionally broken gallery per error type.

## Next Steps
Want to learn more? Check out the full [Documentation](https://mkshp-dev.github.io/obsidian-gallery-plugin/)!
`;
        await this.app.vault.create(`${this.basePath}/00 - Welcome.md`, content);
    }

    private async createLocalSourceNote(): Promise<void> {
        const content = `\
# Local Source Demo

This gallery loads images directly from a folder inside your Obsidian vault.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

## How it works
- \`type: local\` tells the plugin to look for images in your vault.
- \`path: GalleryDemo/Assets\` points to the folder containing the images.
- Change the \`path\` to any folder in your vault that contains images.
- Add \`recursive: true\` to scan all sub-folders as well.
`;
        await this.app.vault.create(`${this.basePath}/01 - Local source.md`, content);
    }

    private async createExternalUrlsNote(): Promise<void> {
        const content = `\
# External URLs Demo

This gallery loads images directly from web URLs.

> **Note:** Remote image loading must be enabled in the Gallery View settings.

\`\`\`obs-gallery
sources:
  - type: external
    urls:
      - https://picsum.photos/400/300?random=1
      - https://picsum.photos/400/300?random=2
      - https://picsum.photos/400/300?random=3
      - https://picsum.photos/400/300?random=4
      - https://picsum.photos/400/300?random=5
      - https://picsum.photos/400/300?random=6
view:
  type: grid
\`\`\`

## How it works
- \`type: external\` tells the plugin these are remote web links.
- Provide a list of direct image links under \`urls\`.
- External images depend on an internet connection to load.
`;
        await this.app.vault.create(`${this.basePath}/02 - External URLs.md`, content);
    }

    private async createViewsNote(): Promise<void> {
        const content = `\
# Views Showcase

The same set of images can be displayed using different layout views.

### Thumbnail View
A responsive grid of uniform tiles — good for large collections.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

---

### Grid View (Masonry)
A Pinterest-style layout that preserves the natural aspect ratio of each image.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: grid
\`\`\`

---

### Carousel View
A horizontal scrolling strip — ideal for a curated set of highlights.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: carousel
\`\`\`
`;
        await this.app.vault.create(`${this.basePath}/03 - Views.md`, content);
    }

    private async createMixedSourcesNote(): Promise<void> {
        const content = `\
# Mixed Sources Demo

You can combine multiple sources into a single gallery. The plugin aggregates all images in order.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
  - type: external
    urls:
      - https://picsum.photos/400/300?random=10
      - https://picsum.photos/400/300?random=11
      - https://picsum.photos/400/300?random=12
view:
  type: grid
\`\`\`

## How it works
- The \`sources\` property is a list — add as many entries as you like.
- You can mix \`local\`, \`external\`, \`immich\`, and \`immich-share\` sources freely.
- Images from each source are shown in declaration order, deduplicated by path.
`;
        await this.app.vault.create(`${this.basePath}/04 - Mixed sources.md`, content);
    }

    private async createSortAndLimitNote(): Promise<void> {
        const content = `\
# Sort and Limit Demo

Control how many images are shown and in what order.

### Most recent 4 images (newest first)

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

### Immich — Latest 10 photos, sorted oldest to newest

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    limit: 10
    sort:
      by: createdAt
      order: asc
view:
  type: carousel
\`\`\`

## Options
| Key | Values | Description |
|---|---|---|
| \`limit\` | any number | Maximum images to display |
| \`sort.by\` | \`createdAt\` | Field to sort by |
| \`sort.order\` | \`asc\` / \`desc\` | Ascending or descending |
`;
        await this.app.vault.create(`${this.basePath}/05 - Sort and limit.md`, content);
    }

    private async createRecursiveAndFiltersNote(): Promise<void> {
        const content = `\
# Recursive Scan and Filters Demo

### Scan all sub-folders recursively

The \`Assets\` folder contains \`Nature/\` and \`Travel/\` sub-folders.
Adding \`recursive: true\` picks up images from all of them.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
    recursive: true
view:
  type: grid
\`\`\`

### Compare: non-recursive (top-level only)

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
    recursive: false
view:
  type: grid
\`\`\`

---

### Immich — Images only, taken this year

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      assetType: image
      createdAfter: "2025-01-01"
    limit: 20
view:
  type: thumbnail
\`\`\`

## Filter options
| Filter | Example | Description |
|---|---|---|
| \`assetType\` | \`image\` or \`video\` | Restrict to photos or videos |
| \`createdAfter\` | \`2025-01-01\` | Only assets after this date (YYYY-MM-DD) |
| \`createdBefore\` | \`2025-12-31\` | Only assets before this date |
| \`isFavorite\` | \`true\` | Only favorited assets |
`;
        await this.app.vault.create(`${this.basePath}/06 - Recursive and filters.md`, content);
    }

    private async createImmichAuthenticatedNote(): Promise<void> {
        const content = `\
# Immich — Authenticated Gallery

Connect Gallery View to your own Immich server with an API key.
Set up your connection in **Settings → Gallery View → Immich Connections** first.

---

### Photos featuring specific people

Use human-readable names — the plugin resolves them to Immich person IDs automatically.

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      people:
        - John Doe
        - Mom
        - Dad
view:
  type: thumbnail
\`\`\`

---

### Photos by tag

Tag names are matched against your Immich tag library automatically.

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      tags:
        - photography
view:
  type: grid
\`\`\`

---

### Work photos

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      tags:
        - work
    limit: 30
    sort:
      by: createdAt
      order: desc
view:
  type: grid
\`\`\`

---

### Study materials (images only, last 2 years)

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      tags:
        - study
      assetType: image
      createdAfter: "2023-01-01"
    limit: 50
view:
  type: carousel
\`\`\`

---

### Combined — Family & photography tag together

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      people:
        - John Doe
        - Mom
        - Dad
      tags:
        - photography
    limit: 20
    sort:
      by: createdAt
      order: desc
view:
  type: grid
\`\`\`

## How it works
- \`connection: home\` refers to the connection key set in plugin settings.
- \`people\` — list of person names as they appear in Immich (case-sensitive).
- \`tags\` — list of tag names as they appear in your Immich tag library.
- Multiple filters are combined (AND logic).
`;
        await this.app.vault.create(`${this.basePath}/07 - Immich authenticated.md`, content);
    }

    private async createImmichFavoritesRecentNote(): Promise<void> {
        const content = `\
# Immich — Favorites and Recent

### All favorited photos

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      isFavorite: true
view:
  type: grid
\`\`\`

---

### Recent 20 photos (newest first)

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    limit: 20
    sort:
      by: createdAt
      order: desc
view:
  type: carousel
\`\`\`

---

### Favorite photos of specific people

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      isFavorite: true
      people:
        - John Doe
    limit: 15
view:
  type: thumbnail
\`\`\`

---

### Favorites from this year

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      isFavorite: true
      createdAfter: "2025-01-01"
    sort:
      by: createdAt
      order: desc
view:
  type: grid
\`\`\`
`;
        await this.app.vault.create(`${this.basePath}/08 - Immich favorites and recent.md`, content);
    }

    private async createImmichAlbumsNote(): Promise<void> {
        const content = `\
# Immich — Albums (Template)

Gallery View can display images from a specific Immich album using the album's ID.

> **Note:** This is a template. Replace \`your-album-id-here\` with an actual album ID from your Immich instance.
> You can find the album ID in the Immich web interface URL when you open an album.

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      albumIds:
        - your-album-id-here
view:
  type: grid
\`\`\`

### Multiple albums in one gallery

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      albumIds:
        - your-first-album-id
        - your-second-album-id
    sort:
      by: createdAt
      order: asc
view:
  type: thumbnail
\`\`\`

## How to find an album ID
1. Open Immich in your browser.
2. Navigate to the album you want.
3. Copy the UUID from the URL (e.g. \`https://your-immich.com/albums/abc-123-def\` → ID is \`abc-123-def\`).
4. Paste it into the \`albumIds\` list above.

> 💡 **Tip:** Use the **"Insert gallery"** command for an interactive picker that finds album IDs for you.
`;
        await this.app.vault.create(`${this.basePath}/09 - Immich albums.md`, content);
    }

    private async createImmichSharedLinkNote(): Promise<void> {
        const content = `\
# Immich Shared Link (Template)

Gallery View can pull images directly from a public Immich shared album — no API key needed.

> **Note:** This is a template. Replace the \`url\` with your own Immich share link.

\`\`\`obs-gallery
sources:
  - type: immich-share
    url: https://your-immich-host.com/share/abcdef123456
view:
  type: grid
\`\`\`

## How to use
1. Create a shared link in your Immich instance (Share → Create link).
2. Paste the full share URL into the \`url\` field above.
3. Gallery View will automatically fetch the images in the share.
`;
        await this.app.vault.create(`${this.basePath}/10 - Immich shared link.md`, content);
    }

    private async createImmichPasswordNote(): Promise<void> {
        const content = `\
# Password-protected Immich Share (Template)

If your Immich shared link requires a password, configure it like this:

> **Note:** This is a template. Replace the \`url\` and \`password\` with your own values.

\`\`\`obs-gallery
sources:
  - type: immich-share
    url: https://your-immich-host.com/share/abcdef123456
    password: my-secret-password
view:
  type: grid
\`\`\`

## How to use
1. Make sure your Immich share is password protected.
2. Paste the share link into \`url\`.
3. Provide the password in the \`password\` field.
`;
        await this.app.vault.create(`${this.basePath}/11 - Password-protected Immich share.md`, content);
    }

    private async createErrorStatesNote(): Promise<void> {
        const lines: string[] = [
            '# Error States Reference',
            '',
            'This note intentionally triggers every possible gallery error so you can see exactly',
            'what the compact error line looks like for each case.',
            '',
            'Each section shows the expected message in a callout, then the broken gallery block that produces it.',
            '',
            '---',
            '',
            '## Config Errors',
            '',
            'These appear when the YAML block itself is malformed.',
            '',
            '### 1 — Empty code block',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Gallery configuration cannot be empty`',
            '',
            '```obs-gallery',
            '```',
            '',
            '---',
            '',
            '### 2 — Bad YAML syntax',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Gallery configuration is empty` or a YAML parse error',
            '',
            '```obs-gallery',
            ': this is not valid yaml [',
            '```',
            '',
            '---',
            '',
            '### 3 — Invalid view type',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: View type must be one of: thumbnail, carousel, grid`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/Assets',
            'view:',
            '  type: slideshow',
            '```',
            '',
            '---',
            '',
            '### 4 — No sources, path, or URLs provided',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Either 'path', 'urls', or 'sources' must be provided`",
            '',
            '```obs-gallery',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 5 — Unknown key in config',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Unknown configuration keys: typo_key`',
            '',
            '```obs-gallery',
            'typo_key: oops',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/Assets',
            '```',
            '',
            '---',
            '',
            '## Content / Path Errors',
            '',
            'These appear when the config is valid but the content cannot be loaded.',
            '',
            '### 6 — Path does not exist',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Path not found: "GalleryDemo/DoesNotExist"`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/DoesNotExist',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '### 7 — Folder exists but is empty',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: No images found in "GalleryDemo/Assets/EmptyFolder"`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/Assets/EmptyFolder',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '### 8 — Unknown source type',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Unsupported source type: dropbox`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: dropbox',
            '    path: /some/path',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '## External / Remote Errors',
            '',
            '### 9 — External images blocked by settings',
            '> [!NOTE] Expected output (when "Allow remote images" is **OFF** in settings)',
            '> `\u26a0\ufe0f gallery: External images blocked — enable "Allow remote images" in plugin settings`',
            '',
            '> **Tip:** Toggle **Settings → Gallery View → Allow remote images** to make this error appear and disappear.',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: external',
            '    urls:',
            '      - https://picsum.photos/400/300?random=99',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '## Immich Errors',
            '',
            '### 10 — Connection key not found in settings',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Immich connection with key 'nonexistent' not found in settings.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: nonexistent',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 11 — Person name not recognised',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Person not found: 'Unknown Person'.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: home',
            '    filters:',
            '      people:',
            '        - Unknown Person',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '### 12 — Tag name not recognised',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Tag not found: 'nonexistenttag'.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: home',
            '    filters:',
            '      tags:',
            '        - nonexistenttag',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 13 — Ambiguous tag name (matches multiple)',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Ambiguous tag name: 'photography' matches multiple tags. Please make the name unique in Immich.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: home',
            '    filters:',
            '      tags:',
            '        - photography',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 14 — Immich share: unreachable host',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: [network or parsing error message]`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich-share',
            '    url: https://not-a-real-immich-host.invalid/share/abc123',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '## Error display mode',
            '',
            'You can control whether errors are shown at all in **Settings → Gallery View → Error display mode**:',
            '',
            '| Mode | What you see |',
            '|---|---|',
            '| Full *(default)* | Compact `\u26a0\ufe0f gallery: …` line |',
            '| Text | Same compact line |',
            '| Hidden | Nothing — errors are silently suppressed |'
        ];

        const content = lines.join('\n') + '\n';
        await this.app.vault.create(`${this.basePath}/12 - Error states.md`, content);
    }
}
