import { App, Notice } from 'obsidian';
import { DUMMY_ASSETS } from './DemoAssets';

export class ShowcaseGenerator {
    private app: App;
    private basePath = 'GalleryDemo';
    private assetsPath = 'GalleryDemo/Assets';

    constructor(app: App) {
        this.app = app;
    }

    async generateShowcase(): Promise<void> {
        try {
            // Check if folder already exists
            const existingFolder = this.app.vault.getAbstractFileByPath(this.basePath);
            if (existingFolder) {
                new Notice(`${this.basePath} already exists. Delete or rename it if you want to regenerate the showcase.`);
                return;
            }

            // Create folders
            await this.createFolderSafe(this.basePath);
            await this.createFolderSafe(this.assetsPath);
            await this.createFolderSafe(`${this.assetsPath}/Nature`);
            await this.createFolderSafe(`${this.assetsPath}/Travel`);
            await this.createFolderSafe(`${this.assetsPath}/EmptyFolder`);

            // Write dummy assets into sub-folders too
            await this.writeDummyAssets();

            // Create showcase notes
            await this.createWelcomeNote();
            await this.createLocalSourceNote();
            await this.createRelativePathNote();
            await this.createExternalUrlsNote();
            await this.createViewsNote();
            await this.createMixedSourcesNote();
            await this.createSortAndLimitNote();
            await this.createRecursiveAndFiltersNote();
            await this.createImmichAuthenticatedNote();
            await this.createImmichFavoritesRecentNote();
            await this.createImmichAlbumsNote();
            await this.createImmichSharedLinkNote();
            await this.createImmichPasswordNote();
            await this.createNextcloudAuthenticatedNote();
            await this.createNextcloudRecursiveAndFiltersNote();
            await this.createNextcloudSharedLinkNote();
            await this.createErrorStatesNote();

            new Notice('Gallery view showcase generated successfully in gallerydemo');
        } catch (error) {
            console.error('Failed to generate showcase:', error);
            new Notice('Failed to generate showcase. Check console for details.');
        }
    }

    private async createFolderSafe(path: string): Promise<void> {
        const exists = await this.app.vault.adapter.exists(path);
        if (!exists) {
            await this.app.vault.adapter.mkdir(path);
        }
    }

    private async writeDummyAssets(): Promise<void> {
        // Split assets across root, Nature, and Travel sub-folders
        const subFolders = [this.assetsPath, `${this.assetsPath}/Nature`, `${this.assetsPath}/Travel`];
        for (let i = 0; i < DUMMY_ASSETS.length; i++) {
            const base64Data = DUMMY_ASSETS[i];
            const binaryString = window.atob(base64Data);
            const bytes = new Uint8Array(binaryString.length);
            for (let j = 0; j < binaryString.length; j++) {
                bytes[j] = binaryString.charCodeAt(j);
            }
            const folder = subFolders[i % subFolders.length];
            await this.app.vault.createBinary(`${folder}/demo-${i + 1}.jpg`, bytes.buffer);
        }
    }

    private async createWelcomeNote(): Promise<void> {
        const content = `\
# Welcome to Gallery View Showcase

This folder (\`GalleryDemo/\`) was generated by the **Gallery View** plugin to help you explore its features.

You are safe to edit, move, or delete any of these files!

> 💡 **Tip:** Use the **"Insert gallery"** command (Cmd/Ctrl + P → "Insert gallery") to build gallery blocks interactively without writing YAML by hand.

## What is this?
These notes contain examples of how to configure image galleries inside your vault.

### 🖼 Local & External Demos
These notes render images immediately:
- [[01 - Local source]] — Load images from a folder in your vault.
- [[Nature (folder note demo)]] — Resolve \`path\` relative to the current note (\`.\`, \`./\`, \`../\`) instead of a hardcoded folder.
- [[02 - External URLs]] — Load images from web URLs.
- [[03 - Views]] — Three layout types: thumbnail, grid, carousel.
- [[04 - Mixed sources]] — Combine local + external in one gallery.
- [[05 - Sort and limit]] — Control order and count of displayed images.
- [[06 - Recursive and filters]] — Scan sub-folders and filter by date or type.

### 🔐 Immich — Authenticated
Connect to your own Immich server using an API key configured in plugin settings:
- [[07 - Immich authenticated]] — People, tags, and date filters.
- [[08 - Immich favorites and recent]] — Favorites and recent photo feeds.
- [[09 - Immich albums]] — Album-based gallery (template).

### 🔗 Immich — Shared Links
No account required, just a public share URL:
- [[10 - Immich shared link]] — Public shared album.
- [[11 - Password-protected Immich share]] — Password-protected share.

### ☁️ Nextcloud — Authenticated
Connect to your Nextcloud server using connection settings (\`nextcloud-demo\`):
- [[12 - Nextcloud authenticated]] — Path selection, subfolders, and view layouts.
- [[13 - Nextcloud recursive and filters]] — Sub-folder scanning, globs, MIME types, sizes, and date filtering.

### 🔗 Nextcloud — Shared Links
No connection settings required, just a public Nextcloud share URL:
- [[14 - Nextcloud shared link]] — Public and password-protected Nextcloud share links.

### ⚠️ Error States Reference
See every compact error the plugin can show — great for debugging your own galleries:
- [[15 - Error states]] — One intentionally broken gallery per error type.

## Next Steps
Want to learn more? Check out the full [Documentation](https://mkshp-dev.github.io/obsidian-gallery-plugin/)!
`;
        await this.app.vault.create(`${this.basePath}/00 - Welcome.md`, content);
    }

    private async createLocalSourceNote(): Promise<void> {
        const content = `\
# Local Source Demo

This gallery loads images directly from a folder inside your Obsidian vault.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

## How it works
- \`type: local\` tells the plugin to look for images in your vault.
- \`path: GalleryDemo/Assets\` points to the folder containing the images.
- Change the \`path\` to any folder in your vault that contains images.
- Add \`recursive: true\` to scan all sub-folders as well.
`;
        await this.app.vault.create(`${this.basePath}/01 - Local source.md`, content);
    }

    private async createRelativePathNote(): Promise<void> {
        const content = `\
# Relative Path Demo (Folder Notes)

Unlike the previous note, **this note lives inside \`${this.assetsPath}/Nature\`** — right next to its own images — instead of pointing at a hardcoded vault path. Rename or move this note along with the \`Nature\` folder and the galleries below keep working.

### This folder's own images (\`path: "."\`)

\`\`\`obs-gallery
sources:
  - type: local
    path: "."
view:
  type: grid
\`\`\`

### A sibling folder's images (\`path: "../Travel"\`)

\`\`\`obs-gallery
sources:
  - type: local
    path: "../Travel"
view:
  type: thumbnail
\`\`\`

## How it works
- \`path: "."\` resolves to the folder that contains **this note** — not a hardcoded vault path.
- \`path: "./Subfolder"\` reaches into a subfolder of the note's folder.
- \`path: "../Sibling"\` steps up one level per \`..\` and reaches into a sibling folder (\`../../Sibling\` steps up two levels, and so on).
- Because the path is resolved relative to the note, renaming or moving this note together with its folder doesn't break the gallery — unlike a hardcoded path such as \`${this.assetsPath}/Nature\`.

> This mirrors the classic "folder note" pattern, where a note shares a name with (and lives inside) the folder it describes.
`;
        await this.app.vault.create(`${this.assetsPath}/Nature/Nature (folder note demo).md`, content);
    }

    private async createExternalUrlsNote(): Promise<void> {
        const content = `\
# External URLs Demo

This gallery loads images directly from web URLs.

> **Note:** Remote image loading must be enabled in the Gallery View settings.

\`\`\`obs-gallery
sources:
  - type: external
    urls:
      - https://picsum.photos/400/300?random=1
      - https://picsum.photos/400/300?random=2
      - https://picsum.photos/400/300?random=3
      - https://picsum.photos/400/300?random=4
      - https://picsum.photos/400/300?random=5
      - https://picsum.photos/400/300?random=6
view:
  type: grid
\`\`\`

## How it works
- \`type: external\` tells the plugin these are remote web links.
- Provide a list of direct image links under \`urls\`.
- External images depend on an internet connection to load.
`;
        await this.app.vault.create(`${this.basePath}/02 - External URLs.md`, content);
    }

    private async createViewsNote(): Promise<void> {
        const content = `\
# Views Showcase

The same set of images can be displayed using different layout views.

### Thumbnail View
A responsive grid of uniform tiles — good for large collections.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

---

### Grid View (Masonry)
A Pinterest-style layout that preserves the natural aspect ratio of each image.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: grid
\`\`\`

---

### Carousel View
A horizontal scrolling strip — ideal for a curated set of highlights.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: carousel
\`\`\`

---

### Embed View
A continuous, borderless vertical stack at natural image size — feels like part of the note, similar to a native \`![[image]]\` embed.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: embed
\`\`\`
`;
        await this.app.vault.create(`${this.basePath}/03 - Views.md`, content);
    }

    private async createMixedSourcesNote(): Promise<void> {
        const content = `\
# Mixed Sources Demo

You can combine multiple sources into a single gallery. The plugin aggregates all images in order.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
  - type: external
    urls:
      - https://picsum.photos/400/300?random=10
      - https://picsum.photos/400/300?random=11
      - https://picsum.photos/400/300?random=12
view:
  type: grid
\`\`\`

## How it works
- The \`sources\` property is a list — add as many entries as you like.
- You can mix \`local\`, \`external\`, \`immich\`, and \`immich-share\` sources freely.
- Images from each source are shown in declaration order, deduplicated by path.
`;
        await this.app.vault.create(`${this.basePath}/04 - Mixed sources.md`, content);
    }

    private async createSortAndLimitNote(): Promise<void> {
        const content = `\
# Sort and Limit Demo

Control how many images are shown and in what order.

### Most recent 4 images (newest first)

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

### Immich — Latest 10 photos, sorted oldest to newest

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    limit: 10
    sort:
      by: createdAt
      order: asc
view:
  type: carousel
\`\`\`

## Options
| Key | Values | Description |
|---|---|---|
| \`limit\` | any number | Maximum images to display |
| \`sort.by\` | \`createdAt\` | Field to sort by |
| \`sort.order\` | \`asc\` / \`desc\` | Ascending or descending |
`;
        await this.app.vault.create(`${this.basePath}/05 - Sort and limit.md`, content);
    }

    private async createRecursiveAndFiltersNote(): Promise<void> {
        const content = `\
# Recursive Scan and Filters Demo

### Scan all sub-folders recursively

The \`Assets\` folder contains \`Nature/\` and \`Travel/\` sub-folders.
Adding \`recursive: true\` picks up images from all of them.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
    recursive: true
view:
  type: grid
\`\`\`

### Compare: non-recursive (top-level only)

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
    recursive: false
view:
  type: grid
\`\`\`

---

### Immich — Images only, taken this year

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      assetType: image
      createdAfter: "2025-01-01"
    limit: 20
view:
  type: thumbnail
\`\`\`

## Filter options
| Filter | Example | Description |
|---|---|---|
| \`assetType\` | \`image\` or \`video\` | Restrict to photos or videos |
| \`createdAfter\` | \`2025-01-01\` | Only assets after this date (YYYY-MM-DD) |
| \`createdBefore\` | \`2025-12-31\` | Only assets before this date |
| \`isFavorite\` | \`true\` | Only favorited assets |
`;
        await this.app.vault.create(`${this.basePath}/06 - Recursive and filters.md`, content);
    }

    private async createImmichAuthenticatedNote(): Promise<void> {
        const content = `\
# Immich — Authenticated Gallery

Connect Gallery View to your own Immich server with an API key.
Set up your connection in **Settings → Gallery View → Immich Connections** first.

---

### Photos featuring specific people

Use human-readable names — the plugin resolves them to Immich person IDs automatically.

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      people:
        - John Doe
        - Mom
        - Dad
view:
  type: thumbnail
\`\`\`

---

### Photos by tag

Tag names are matched against your Immich tag library automatically.

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      tags:
        - photography
view:
  type: grid
\`\`\`

---

### Work photos

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      tags:
        - work
    limit: 30
    sort:
      by: createdAt
      order: desc
view:
  type: grid
\`\`\`

---

### Study materials (images only, last 2 years)

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      tags:
        - study
      assetType: image
      createdAfter: "2023-01-01"
    limit: 50
view:
  type: carousel
\`\`\`

---

### Combined — Family & photography tag together

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      people:
        - John Doe
        - Mom
        - Dad
      tags:
        - photography
    limit: 20
    sort:
      by: createdAt
      order: desc
view:
  type: grid
\`\`\`

## How it works
- \`connection: home\` refers to the connection key set in plugin settings.
- \`people\` — list of person names as they appear in Immich (case-sensitive).
- \`tags\` — list of tag names as they appear in your Immich tag library.
- Multiple filters are combined (AND logic).
`;
        await this.app.vault.create(`${this.basePath}/07 - Immich authenticated.md`, content);
    }

    private async createImmichFavoritesRecentNote(): Promise<void> {
        const content = `\
# Immich — Favorites and Recent

### All favorited photos

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      isFavorite: true
view:
  type: grid
\`\`\`

---

### Recent 20 photos (newest first)

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    limit: 20
    sort:
      by: createdAt
      order: desc
view:
  type: carousel
\`\`\`

---

### Favorite photos of specific people

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      isFavorite: true
      people:
        - John Doe
    limit: 15
view:
  type: thumbnail
\`\`\`

---

### Favorites from this year

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      isFavorite: true
      createdAfter: "2025-01-01"
    sort:
      by: createdAt
      order: desc
view:
  type: grid
\`\`\`
`;
        await this.app.vault.create(`${this.basePath}/08 - Immich favorites and recent.md`, content);
    }

    private async createImmichAlbumsNote(): Promise<void> {
        const content = `\
# Immich — Albums (Template)

Gallery View can display images from a specific Immich album using the album's ID.

> **Note:** This is a template. Replace \`your-album-id-here\` with an actual album ID from your Immich instance.
> You can find the album ID in the Immich web interface URL when you open an album.

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      albumIds:
        - your-album-id-here
view:
  type: grid
\`\`\`

### Multiple albums in one gallery

\`\`\`obs-gallery
sources:
  - type: immich
    connection: home
    filters:
      albumIds:
        - your-first-album-id
        - your-second-album-id
    sort:
      by: createdAt
      order: asc
view:
  type: thumbnail
\`\`\`

## How to find an album ID
1. Open Immich in your browser.
2. Navigate to the album you want.
3. Copy the UUID from the URL (e.g. \`https://your-immich.com/albums/abc-123-def\` → ID is \`abc-123-def\`).
4. Paste it into the \`albumIds\` list above.

> 💡 **Tip:** Use the **"Insert gallery"** command for an interactive picker that finds album IDs for you.
`;
        await this.app.vault.create(`${this.basePath}/09 - Immich albums.md`, content);
    }

    private async createImmichSharedLinkNote(): Promise<void> {
        const content = `\
# Immich Shared Link (Template)

Gallery View can pull images directly from a public Immich shared album — no API key needed.

> **Note:** This is a template. Replace the \`url\` with your own Immich share link.

\`\`\`obs-gallery
sources:
  - type: immich-share
    url: https://your-immich-host.com/share/abcdef123456
view:
  type: grid
\`\`\`

## How to use
1. Create a shared link in your Immich instance (Share → Create link).
2. Paste the full share URL into the \`url\` field above.
3. Gallery View will automatically fetch the images in the share.
`;
        await this.app.vault.create(`${this.basePath}/10 - Immich shared link.md`, content);
    }

    private async createImmichPasswordNote(): Promise<void> {
        const content = `\
# Password-protected Immich Share (Template)

If your Immich shared link requires a password, configure it like this:

> **Note:** This is a template. Replace the \`url\` and \`password\` with your own values.

\`\`\`obs-gallery
sources:
  - type: immich-share
    url: https://your-immich-host.com/share/abcdef123456
    password: my-secret-password
view:
  type: grid
\`\`\`

## How to use
1. Make sure your Immich share is password protected.
2. Paste the share link into \`url\`.
3. Provide the password in the \`password\` field.
`;
        await this.app.vault.create(`${this.basePath}/11 - Password-protected Immich share.md`, content);
    }

    private async createNextcloudAuthenticatedNote(): Promise<void> {
        const content = `\
# Nextcloud — Authenticated Gallery

Connect Gallery View to your Nextcloud instance using connection settings configured in **Settings → Gallery View → Nextcloud Connections**.

> **Note:** Configure a Nextcloud connection with key \`nextcloud-demo\` in plugin settings to preview these galleries.

---

### Root gallery folder (\`/Gallery-Test\`)

Loads images from the \`/Gallery-Test\` folder on your Nextcloud server.

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test
view:
  type: grid
\`\`\`

---

### Specific subfolder (\`/Gallery-Test/Vacation\`)

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test/Vacation
view:
  type: thumbnail
\`\`\`

---

### Carousel view layout

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test
view:
  type: carousel
\`\`\`

## How it works
- \`type: nextcloud\` tells the plugin to load images from Nextcloud via WebDAV.
- \`connection: nextcloud-demo\` refers to the connection key configured in Nextcloud settings.
- \`path\` specifies the folder path on your Nextcloud server.
`;
        await this.app.vault.create(`${this.basePath}/12 - Nextcloud authenticated.md`, content);
    }

    private async createNextcloudRecursiveAndFiltersNote(): Promise<void> {
        const content = `\
# Nextcloud — Recursive Scan and Filters

Combine Nextcloud sources with advanced filters, glob pattern matching, and sorting options.

---

### Recursive scanning (all subfolders)

Adding \`recursive: true\` scans sub-folders such as \`Vacation/\`, \`Nature/\`, and \`Archive/2023/\`.

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test
    recursive: true
view:
  type: grid
\`\`\`

---

### Filename pattern matching (\`filenameFilter\`)

Only load images whose names match the glob pattern \`IMG_*\`.

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test
    recursive: true
    filenameFilter: "IMG_*"
view:
  type: thumbnail
\`\`\`

---

### Filter by MIME types & file size

Only load JPEG and PNG files that are at least 10 KB in size.

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test
    recursive: true
    filters:
      mimeTypes:
        - image/jpeg
        - image/png
      minSizeKb: 10
      maxSizeKb: 5000
view:
  type: grid
\`\`\`

---

### Sorting & limit

Show the 10 most recently modified images.

\`\`\`obs-gallery
sources:
  - type: nextcloud
    connection: nextcloud-demo
    path: /Gallery-Test
    recursive: true
    sort:
      by: lastModified
      order: desc
    limit: 10
view:
  type: carousel
\`\`\`

## Filter options
| Option | Example | Description |
|---|---|---|
| \`recursive\` | \`true\` / \`false\` | Scan subdirectories recursively |
| \`filenameFilter\` | \`"IMG_*"\` / \`"*.png"\` | Glob pattern filter for file names |
| \`filters.mimeTypes\` | \`["image/jpeg", "image/png"]\` | Filter by image MIME type |
| \`filters.minSizeKb\` / \`maxSizeKb\` | \`10\` / \`5000\` | Filter by file size range in KB |
| \`filters.modifiedAfter\` / \`modifiedBefore\` | \`"2024-01-01"\` | Filter by modification date |
| \`sort.by\` | \`name\` / \`size\` / \`lastModified\` | Field to sort files by |
| \`sort.order\` | \`asc\` / \`desc\` | Ascending or descending order |
| \`limit\` | \`10\` | Maximum number of images to fetch |
`;
        await this.app.vault.create(`${this.basePath}/13 - Nextcloud recursive and filters.md`, content);
    }

    private async createNextcloudSharedLinkNote(): Promise<void> {
        const content = `\
# Nextcloud Shared Links (Public & Password-Protected)

Gallery View can display images directly from a public Nextcloud share link — no account or login settings required.

---

### Standard Public Share Link

Paste any public Nextcloud folder share URL.

\`\`\`obs-gallery
sources:
  - type: nextcloud-share
    url: https://use23.thegood.cloud/s/YOUR_SHARE_TOKEN
view:
  type: grid
\`\`\`

---

### Password-Protected Nextcloud Share

If your Nextcloud public share link is protected with a password, specify it in the \`password\` field.

\`\`\`obs-gallery
sources:
  - type: nextcloud-share
    url: https://use23.thegood.cloud/s/YOUR_PROTECTED_SHARE_TOKEN
    password: my-secret-password
view:
  type: grid
\`\`\`

---

### Nextcloud Photos App Public Album

If you create a public album link in the Nextcloud Photos app:

\`\`\`obs-gallery
sources:
  - type: nextcloud-share
    url: https://use23.thegood.cloud/apps/photos/public/YOUR_ALBUM_TOKEN
view:
  type: thumbnail
\`\`\`

## How to use
1. Open Nextcloud in your browser.
2. Select a folder or photo album and click **Share**.
3. Create a public share link (optionally set a password).
4. Copy and paste the share URL into the \`url\` field above.
`;
        await this.app.vault.create(`${this.basePath}/14 - Nextcloud shared link.md`, content);
    }

    private async createErrorStatesNote(): Promise<void> {
        const lines: string[] = [
            '# Error States Reference',
            '',
            'This note intentionally triggers every possible gallery error so you can see exactly',
            'what the compact error line looks like for each case.',
            '',
            'Each section shows the expected message in a callout, then the broken gallery block that produces it.',
            '',
            '---',
            '',
            '## Config Errors',
            '',
            'These appear when the YAML block itself is malformed.',
            '',
            '### 1 — Empty code block',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Gallery configuration cannot be empty`',
            '',
            '```obs-gallery',
            '```',
            '',
            '---',
            '',
            '### 2 — Bad YAML syntax',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Gallery configuration is empty` or a YAML parse error',
            '',
            '```obs-gallery',
            ': this is not valid yaml [',
            '```',
            '',
            '---',
            '',
            '### 3 — Invalid view type',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: View type must be one of: thumbnail, carousel, grid, embed`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/Assets',
            'view:',
            '  type: slideshow',
            '```',
            '',
            '---',
            '',
            '### 4 — No sources, path, or URLs provided',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Either 'path', 'urls', or 'sources' must be provided`",
            '',
            '```obs-gallery',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 5 — Unknown key in config',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Unknown configuration keys: typo_key`',
            '',
            '```obs-gallery',
            'typo_key: oops',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/Assets',
            '```',
            '',
            '---',
            '',
            '## Content / Path Errors',
            '',
            'These appear when the config is valid but the content cannot be loaded.',
            '',
            '### 6 — Path does not exist',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Path not found: "GalleryDemo/DoesNotExist"`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/DoesNotExist',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '### 7 — Folder exists but is empty',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: No images found in "GalleryDemo/Assets/EmptyFolder"`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: local',
            '    path: GalleryDemo/Assets/EmptyFolder',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '### 8 — Unknown source type',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Unsupported source type: dropbox`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: dropbox',
            '    path: /some/path',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '## External / Remote Errors',
            '',
            '### 9 — External images blocked by settings',
            '> [!NOTE] Expected output (when "Allow remote images" is **OFF** in settings)',
            '> `\u26a0\ufe0f gallery: External images blocked — enable "Allow remote images" in plugin settings`',
            '',
            '> **Tip:** Toggle **Settings → Gallery View → Allow remote images** to make this error appear and disappear.',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: external',
            '    urls:',
            '      - https://picsum.photos/400/300?random=99',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '## Immich Errors',
            '',
            '### 10 — Connection key not found in settings',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Immich connection with key 'nonexistent' not found in settings.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: nonexistent',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 11 — Person name not recognised',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Person not found: 'Unknown Person'.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: home',
            '    filters:',
            '      people:',
            '        - Unknown Person',
            'view:',
            '  type: thumbnail',
            '```',
            '',
            '---',
            '',
            '### 12 — Tag name not recognised',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Tag not found: 'nonexistenttag'.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: home',
            '    filters:',
            '      tags:',
            '        - nonexistenttag',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 13 — Ambiguous tag name (matches multiple)',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Ambiguous tag name: 'photography' matches multiple tags. Please make the name unique in Immich.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich',
            '    connection: home',
            '    filters:',
            '      tags:',
            '        - photography',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 14 — Immich share: unreachable host',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: [network or parsing error message]`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: immich-share',
            '    url: https://not-a-real-immich-host.invalid/share/abc123',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '## Nextcloud Errors',
            '',
            '### 15 — Nextcloud: Missing connection reference',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Nextcloud source is missing a 'connection' reference.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: nextcloud',
            '    path: /Gallery-Test',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 16 — Nextcloud: Connection key not found in settings',
            '> [!NOTE] Expected output',
            "> `\u26a0\ufe0f gallery: Nextcloud connection with key 'nonexistent' not found in settings.`",
            '',
            '```obs-gallery',
            'sources:',
            '  - type: nextcloud',
            '    connection: nonexistent',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 17 — Nextcloud share: Missing URL',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Nextcloud share source is missing a URL.`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: nextcloud-share',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '### 18 — Nextcloud share: Invalid URL format',
            '> [!NOTE] Expected output',
            '> `\u26a0\ufe0f gallery: Invalid Nextcloud share URL: https://invalid-share-link.example.com`',
            '',
            '```obs-gallery',
            'sources:',
            '  - type: nextcloud-share',
            '    url: https://invalid-share-link.example.com',
            'view:',
            '  type: grid',
            '```',
            '',
            '---',
            '',
            '## Error display mode',
            '',
            'You can control whether errors are shown at all in **Settings → Gallery View → Error display mode**:',
            '',
            '| Mode | What you see |',
            '|---|---|',
            '| Full *(default)* | Compact `\u26a0\ufe0f gallery: …` line |',
            '| Text | Same compact line |',
            '| Hidden | Nothing — errors are silently suppressed |'
        ];

        const content = lines.join('\n') + '\n';
        await this.app.vault.create(`${this.basePath}/15 - Error states.md`, content);
    }
}
