import { App, Notice } from 'obsidian';
import { DUMMY_ASSETS } from './DemoAssets';

export class ShowcaseGenerator {
    private app: App;
    private basePath = 'GalleryDemo';
    private assetsPath = 'GalleryDemo/Assets';

    constructor(app: App) {
        this.app = app;
    }

    async generateShowcase(): Promise<void> {
        try {
            // Check if folder already exists
            const existingFolder = this.app.vault.getAbstractFileByPath(this.basePath);
            if (existingFolder) {
                new Notice(`${this.basePath} already exists. Delete or rename it if you want to regenerate the showcase.`);
                return;
            }

            // Create folders
            await this.createFolderSafe(this.basePath);
            await this.createFolderSafe(this.assetsPath);

            // Write dummy assets
            await this.writeDummyAssets();

            // Create showcase notes
            await this.createWelcomeNote();
            await this.createLocalSourceNote();
            await this.createExternalUrlsNote();
            await this.createViewsNote();
            await this.createMixedSourcesNote();
            await this.createImmichSharedLinkNote();
            await this.createImmichPasswordNote();

            new Notice('Gallery view showcase generated successfully in gallerydemo');
        } catch (error) {
            console.error('Failed to generate showcase:', error);
            new Notice('Failed to generate showcase. Check console for details.');
        }
    }

    private async createFolderSafe(path: string): Promise<void> {
        try {
            // eslint-disable-next-line obsidianmd/no-unsupported-api
            await this.app.vault.createFolder(path);
        } catch (e) {
            // Error when folder already exists in some vault implementations
            if (e instanceof Error && e.message.includes('Folder already exists')) {
                return;
            }
            throw e;
        }
    }

    private async writeDummyAssets(): Promise<void> {
        for (let i = 0; i < DUMMY_ASSETS.length; i++) {
            const base64Data = DUMMY_ASSETS[i];
            const binaryString = window.atob(base64Data);
            const bytes = new Uint8Array(binaryString.length);
            for (let j = 0; j < binaryString.length; j++) {
                bytes[j] = binaryString.charCodeAt(j);
            }
            await this.app.vault.createBinary(`${this.assetsPath}/demo-${i + 1}.jpg`, bytes.buffer);
        }
    }

    private async createWelcomeNote(): Promise<void> {
        const content = `\
# Welcome to Gallery View Showcase

This folder (\`GalleryDemo/\`) was generated by the **Gallery View** plugin to help you explore its features.

You are safe to edit, move, or delete any of these files!

## What is this?
These notes contain examples of how to configure image galleries inside your vault.

### 🖼 Working Demos
These notes should render images immediately:
- [[01 - Local source]] - Shows how to load images from a folder in your vault.
- [[02 - External URLs]] - Shows how to load images from the web.
- [[03 - Views]] - Demonstrates different layout types (thumbnail, grid, carousel).
- [[04 - Mixed sources]] - Shows how to combine multiple sources in one gallery.

### 📝 Templates
These notes are starting points for integrating with external services:
- [[05 - Immich shared link]] - How to load an Immich shared album.
- [[06 - Password-protected Immich share]] - How to authenticate an Immich share.

## Next Steps
Want to learn more? Check out the full [Documentation](https://mkshp-dev.github.io/obsidian-gallery-plugin/)!
`;
        await this.app.vault.create(`${this.basePath}/00 - Welcome.md`, content);
    }

    private async createLocalSourceNote(): Promise<void> {
        const content = `\
# Local Source Demo

This gallery loads images directly from a folder inside your Obsidian vault.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

## How it works
- \`type: local\` tells the plugin to look for images in your vault.
- \`path: GalleryDemo/Assets\` points to the folder containing the images.
- Change the \`path\` to any folder in your vault that contains images.
- If you have nested folders, you can add \`recursive: true\` to the source block to scan subfolders.
`;
        await this.app.vault.create(`${this.basePath}/01 - Local source.md`, content);
    }

    private async createExternalUrlsNote(): Promise<void> {
        const content = `\
# External URLs Demo

This gallery loads images directly from web URLs.

> **Note:** Remote image loading must be enabled in the Gallery View settings.

\`\`\`obs-gallery
sources:
  - type: external
    urls:
      - https://picsum.photos/400/300?random=1
      - https://picsum.photos/400/300?random=2
      - https://picsum.photos/400/300?random=3
      - https://picsum.photos/400/300?random=4
view:
  type: grid
\`\`\`

## How it works
- \`type: external\` tells the plugin these are remote web links.
- Provide a list of direct image links under \`urls\`.
- External images depend on an internet connection to load.
`;
        await this.app.vault.create(`${this.basePath}/02 - External URLs.md`, content);
    }

    private async createViewsNote(): Promise<void> {
        const content = `\
# Views Showcase

The same set of images can be displayed using different layout views.

### Thumbnail View
A standard responsive grid of square thumbnails.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: thumbnail
\`\`\`

---

### Grid View (Masonry)
A Pinterest-style layout that preserves aspect ratios.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: grid
\`\`\`

---

### Carousel View
A horizontal scrolling gallery.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
view:
  type: carousel
\`\`\`
`;
        await this.app.vault.create(`${this.basePath}/03 - Views.md`, content);
    }

    private async createMixedSourcesNote(): Promise<void> {
        const content = `\
# Mixed Sources Demo

You can combine multiple sources into a single gallery! The plugin will aggregate all the images.

\`\`\`obs-gallery
sources:
  - type: local
    path: GalleryDemo/Assets
  - type: external
    urls:
      - https://picsum.photos/400/300?random=5
      - https://picsum.photos/400/300?random=6
view:
  type: grid
\`\`\`

## How it works
- The \`sources\` property is a list.
- You can mix and match \`local\`, \`external\`, and other source types.
- The gallery processor combines them and renders them in the chosen \`view\`.
`;
        await this.app.vault.create(`${this.basePath}/04 - Mixed sources.md`, content);
    }

    private async createImmichSharedLinkNote(): Promise<void> {
        const content = `\
# Immich Shared Link (Template)

Gallery View can pull images directly from a public Immich shared album.

> **Note:** This is a template note. The gallery below will not work until you replace the \`url\` with your own Immich share link.

\`\`\`obs-gallery
sources:
  - type: immich-share
    url: https://your-immich-host.com/share/abcdef123456
view:
  type: grid
\`\`\`

## How to use
1. Create a shared link in your Immich instance.
2. Paste the full share URL into the \`url\` field above.
3. Gallery View will automatically fetch the images in the share.
`;
        await this.app.vault.create(`${this.basePath}/05 - Immich shared link.md`, content);
    }

    private async createImmichPasswordNote(): Promise<void> {
        const content = `\
# Password-protected Immich Share (Template)

If your Immich shared link requires a password, you can configure it like this:

> **Note:** This is a template note. Replace the \`url\` and \`password\` with your own values.

\`\`\`obs-gallery
sources:
  - type: immich-share
    url: https://your-immich-host.com/share/abcdef123456
    password: my-secret-password
view:
  type: grid
\`\`\`

## How to use
1. Make sure your Immich share is password protected.
2. Paste the link into \`url\`.
3. Provide the password in the \`password\` field.
`;
        await this.app.vault.create(`${this.basePath}/06 - Password-protected Immich share.md`, content);
    }
}
